# Generated by Django 4.0.5 on 2023-08-20 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultadoevaluacion',
            old_name='resultado_stsg',
            new_name='resultado_stsg_e',
        ),
        migrations.AddField(
            model_name='resultadoevaluacion',
            name='resultado_stsg_r',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
