# Generated by Django 4.0.5 on 2023-08-20 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0002_rename_resultado_stsg_resultadoevaluacion_resultado_stsg_e_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultadoevaluacion',
            old_name='fecha_nacimiento',
            new_name='fecha_evaluacion',
        ),
    ]
